export const FETCH_ACTIONS = {
    PROGRESS: 'progress',
    SUCCESS: 'success',
    ERROR: 'error',
   
};

export const CART_ACTIONS = {
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    CHANGE_CART_QTY: "CHANGE_CART_QTY",
};


export const FILTER_ACTIONS = {
    SORT_BY_PRICE: "SORT_BY_PRICE",
    FILTER_BY_STOCK: "FILTER_BY_STOCK",
    FILTER_BY_DELIVERY: "FILTER_BY_DELIVERY",
    FILTER_BY_RATING: "FILTER_BY_RATING",
    FILTER_BY_SEARCH: "FILTER_BY_SEARCH",
    CLEAR_FILTER: "CLEAR_FILTER",
};